## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

dist: xenial

os:
  - linux
  #- osx
  
env:
  - JULIA_CMDSTAN_HOME="$HOME/cmdstan-2.21.0/"
  
before_install:
  - OLDWD=`pwd`
  - cd ~
  - wget https://github.com/stan-dev/cmdstan/releases/download/v2.21.0/cmdstan-2.21.0.tar.gz
  - tar -xzpf cmdstan-2.21.0.tar.gz
  - make -C $JULIA_CMDSTAN_HOME build
  - cd $OLDWD
  
julia:
  #- 1.2
  - 1.3
  - nightly
  
notifications:
  email: false
  
git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly
  - os: osx

#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - travis_wait 30 julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

#jobs:
#  include:
#    - stage: Test
#      julia: 1.3
#      os: linux
#    - stage: Documentation
#      julia: 1.3
#      os: linux
#      script:
#        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
#        - travis_wait 20 julia --project=docs --color=yes docs/make.jl
#      after_success: skip

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
