name = "Stan"
uuid = "682df890-35be-576f-97d0-3d8c8b33a550"
license = "MIT"
desc = "Illustrate StanJulia's interface options to cmdstan"
authors = ["Rob J Goedman <goedman@icloud.com>"]
version = "6.0.8"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StanBase = "d0ee94f6-a23d-54aa-bbe9-7f572d6da7f5"
StanDiagnose = "fb13fc95-9a72-5e81-90ef-432a29d7f4c2"
StanOptimize = "fbd8da12-e93d-5a64-9231-612a0707ab99"
StanSample = "c1514b29-d3a0-5178-b312-660c88baa699"
StanVariational = "6ede68ce-8466-5085-8a79-4c4de3d9cf4a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "0.21"
DocStringExtensions = "0.8"
StanBase = "2.0"
StanDiagnose = "2.0"
StanOptimize = "2.0"
StanSample = "2.0"
StanVariational = "2.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
