name = "Stan"
uuid = "682df890-35be-576f-97d0-3d8c8b33a550"
license = "MIT"
desc = "Illustrate StanJulia's interface options to cmdstan"
authors = ["Rob J Goedman <goedman@icloud.com>"]
version = "10.4.0"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CompatHelperLocal = "5224ae11-6099-4aaa-941d-3aab004bd678"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InferenceObjects = "b5cf5a8d-e756-4ee3-b014-01d49d192c00"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PosteriorDB = "1c4bc282-d2f5-44f9-b6d1-8c4424a23ad4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StanBase = "d0ee94f6-a23d-54aa-bbe9-7f572d6da7f5"
StanDiagnose = "fb13fc95-9a72-5e81-90ef-432a29d7f4c2"
StanOptimize = "fbd8da12-e93d-5a64-9231-612a0707ab99"
StanQuap = "e4723793-2808-4fc5-8a98-c57f4c160c53"
StanSample = "c1514b29-d3a0-5178-b312-660c88baa699"
StanVariational = "6ede68ce-8466-5085-8a79-4c4de3d9cf4a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AxisKeys = "0.2"
CSV = "0.10"
CompatHelperLocal = "0.1"
DataFrames = "1.4"
DataStructures = "0.18.13"
DimensionalData = "0.24"
Distributions = "0.25"
DocStringExtensions = "0.9"
InferenceObjects = "0.3.4"
JSON = "0.21"
JSON3 = "1.12"
MCMCChains = "5.6, 6"
MonteCarloMeasurements = "1.0"
NamedArrays = "0.9"
NamedTupleTools = "0.14"
OrderedCollections = "1.4.1"
PosteriorDB = "0.4"
StanBase = "4"
StanDiagnose = "4.4"
StanOptimize = "4"
StanQuap = "4"
StanSample = "7"
StanVariational = "4.3"
StatsBase = "0.33, 0.34"
StatsFuns = "1"
Tables = "1.10"
julia = "1"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
